blueprint:
  name: Universal Auto Turn Off (Reboot-Safe)
  description: >
    Automatically turns off any switch, light, input_boolean, or climate entity
    after it has been continuously active for a specified duration.
    This version is reboot-safe and uses `for:` logic to persist across restarts.
  domain: automation
  input:
    target_entity:
      name: Target Entity
      description: Entity to monitor and auto-turn-off
      selector:
        entity:
          domain:
            - switch
            - light
            - input_boolean
            - climate

    max_on_duration:
      name: Max On Duration
      description: Time before entity should be turned off
      default: "01:00:00"
      selector:
        duration:

mode: single

variables:
  entity_id: !input target_entity
  entity_domain: "{{ entity_id.split('.')[0] }}"

trigger:
  - platform: state
    entity_id: !input target_entity
    to:
      - "on"
      - "heat"
      - "cool"
      - "auto"
      - "idle"
    for: !input max_on_duration

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ entity_domain in ['switch', 'light', 'input_boolean'] }}"
        sequence:
          - service: "{{ entity_domain }}.turn_off"
            target:
              entity_id: "{{ entity_id }}"

      - conditions:
          - condition: template
            value_template: "{{ entity_domain == 'climate' }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: "{{ entity_id }}"
            data:
              hvac_mode: "off"